//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC_2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC_2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-11 z: zzzzzdzzzzlzz
        ///3-7 x: xjxbgpxxgtx
        ///3-4 v: vvmv
        ///3-5 t: tgkfq
        ///9-10 j: jjjjjjjjqjjjj
        ///5-7 r: rnhrhrr
        ///2-6 n: gnntnnsnnqjsbrn
        ///3-4 g: vrggfvxsgmggkgsm
        ///1-4 c: brccqr
        ///1-5 h: hhhzzvcdhhhhhhhh
        ///4-11 c: ncnqbzlkckc
        ///1-13 q: hqqqqqqqqqqqlq
        ///8-9 h: hhhhhhxxkh
        ///3-9 b: bbbbsfbbc
        ///3-8 k: zfqzkzgk
        ///3-9 k: wjkwhnkkfvxk
        ///3-11 v: vgkvvcjvvvv
        ///5-6 l: llllhr
        ///9-11 z: lzzzgzzmzzdzzz
        ///13-16 w: wwlwwwwlwwxwwfwf
        ///8-11 r: rrrrrrrrrrcrdrr
        ///1-9 v: mlvvvxnwrwvv
        ///4-6 z: mzzzzz
        ///3-4 s: svsj
        ///8-11 w: wwwwwwwjwwww
        ///10-13 r: dr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exercise_02 {
            get {
                return ResourceManager.GetString("Exercise_02", resourceCulture);
            }
        }
    }
}
